# -*- coding: utf-8 -*-
"""clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbDNPWgzceUxoEIK-JZwho8N9owXvsip

#IMPORTAR LIBRERIAS
"""

import pandas as pd
import numpy as np

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

#en esta subieremos el raw
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline-2516232022/refs/heads/main/data/raw/F_clientes.csv"

clientes = pd.read_csv(url)

clientes.head()

cliente.info()

clientes.isnull().sum()

clientes.duplicated().sum()

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes = clientes.drop_duplicates()

#Eliminar Duplicados
def eliminar_duplicados(df):
    return df.drop_duplicates()

#Modificacion de telefono
def formatear_telefono(df):
    df["telefono"] = df["telefono"].astype(str).str.replace(r"\D", "", regex=True)
    df["telefono"] = df["telefono"].apply(
        lambda x: x[:4] + "-" + x[4:] if len(x) == 8 else x
    )
    return df

clientes["cliente"] = clientes["cliente"].astype(str)
clientes["cliente"] = clientes["cliente"].str.replace(r"\s\d+$", "", regex=True)
clientes["cliente"] = clientes["cliente"].str.strip()

columnas_obligatorias = [
    "id_cliente",
    "cliente",
    "correo",
    "telefono"
]

validos = clientes [
 clientes[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = clientes [
 clientes[columnas_obligatorias].notna().all(axis=1)
].copy()

def motivo_rechazo(row):
    motivos = []

    if pd.isna(row["id_cliente"]):
        motivos.append("id_cliente_nulo")

    if pd.isna(row["cliente"]):
        motivos.append("cliente_nulo")

    if pd.isna(row["correo"]):
        motivos.append("correo_nulo")

    if pd.isna(row["telefono"]):
        motivos.append("telefono_nulo")

    return ", ".join(motivos)

validos.to_csv("clientes_curated.csv", index=False)
rechazados.to_csv("clientes_rejects.csv", index=False)

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()