# -*- coding: utf-8 -*-
"""envios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jtrFKjUgUKLpYOe9rCvoMSfWgdZslvH
"""

import pandas as pd
import numpy as np

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

#en esta subieremos el raw
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline-2516232022/refs/heads/main/data/raw/F_envios.csv"

envios = pd.read_csv(url)

envios.info()

envios.isnull().sum()

envios.duplicated().sum()

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

envios = normalizar_columnas(envios)
envios = limpiar_texto(envios)
envios = envios.drop_duplicates()

#Eliminar Duplicados
def eliminar_duplicados(df):
    return df.drop_duplicates()

envios["fecha_envio"] = pd.to_datetime(
    envios["fecha_envio"].astype(str).str.strip(),
    errors="coerce",
    dayfirst=True
)

envios.info()

def validar_id(valor):
    import pandas as pd

    if pd.isna(valor):
        return False

    try:
        return int(valor) > 0
    except:
        return False

def validar_fila(row):
    errores = []

    # id_envio
    if not validar_id(row["id_envio"]):
        errores.append("id_envio_invalido")

    # id_pedido
    if not validar_id(row["id_pedido"]):
        errores.append("id_pedido_invalido")

    # direccion
    if pd.isna(row["direccion"]):
        errores.append("direccion_nula")

    # fecha
    if pd.isna(row["fecha_envio"]):
        errores.append("fecha_envio_invalida")

    # estado
    estados_validos = ["pendiente", "enviado", "entregado"]
    if row["estado_envio"] not in estados_validos:
        errores.append("estado_envio_invalido")

    return ", ".join(errores)

columnas_obligatorias = [
    "id_envio",
    "id_pedido",
    "direccion",
    "fecha_envio",
    "estado_envio"
]

validos = envios [
 envios[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = envios [
 envios[columnas_obligatorias].notna().all(axis=1)
].copy()

validos.to_csv("envios_curated.csv", index=False)
rechazados.to_csv("envios_rejects.csv", index=False)

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()