# -*- coding: utf-8 -*-
"""pedidos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgD3cyriZ0FCuEtTZ9ad5Rpmijl2gIpO
"""

import pandas as pd
import numpy as np

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

#en esta subieremos el raw
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline-2516232022/refs/heads/main/data/raw/F_pedidos.csv"

pedidos = pd.read_csv(url)

pedidos.info()

pedidos.isnull().sum()

pedidos.duplicated().sum()

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

pedidos = normalizar_columnas(pedidos)
pedidos = limpiar_texto(pedidos)
pedidos = pedidos.drop_duplicates()

#Eliminar Duplicados
def eliminar_duplicados(df):
    return df.drop_duplicates()

#convertir fecha a datetime
pedidos["fecha_pedido"] = pd.to_datetime(
    pedidos["fecha_pedido"].astype(str).str.strip(),
    errors="coerce",
    dayfirst=True
)

pedidos.info()

#convertir monto en float
pedidos["monto"] = (

   pedidos["monto"]
   .astype(str)
   .str.replace(",",".",regex=False)
)

#Convertir decimal
pedidos["monto"] = pd.to_numeric(
    pedidos["monto"],
    errors="coerce"
)

columnas_obligatorias = [
    "id_pedido",
    "id_cliente",
    "fecha_pedido",
    "monto",
    "estado"
]

validos = pedidos [
 pedidos[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = pedidos [
 pedidos[columnas_obligatorias].notna().all(axis=1)
].copy()

def motivo_rechazo(row):
    motivos = []

    if pd.isna(row["id_pedido"]):
        motivos.append("id_pedido_nulo")

    if pd.isna(row["id_cliente"]):
        motivos.append("id_cliente_nulo")

    if pd.isna(row["fecha_pedido"]):
        motivos.append("fecha_pedido_nulo")

    if pd.isna(row["monto"]):
        motivos.append("monto_nulo")

    if pd.isna(row["estado"]):
        motivos.append("estado_nulo")

    return ", ".join(motivos)

# APLICAR MOTIVOS A LOS RECHAZADOS
rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo, axis=1)

validos.to_csv("pedidos_curated.csv", index=False)
rechazados.to_csv("pedidos_rejects.csv", index=False)

validos.head()

validos.dtypes

validos.isnull().sum()

validos.value_counts()